---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: Coverage
run-name: >-
  Analysing Coverage for ${{ github.event.pull_request.title || github.sha }}

concurrency:
  group: ${{ github.repository }}:${{ github.ref }}:coverage
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  coverage:
    name: codecov
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkout the repository
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout the Repository
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        # yamllint disable-line rule:line-length
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          cache: true

      - name: Install go-junit-report
        # yamllint disable rule:line-length
        run: |-
          # go install github.com/jstemmer/go-junit-report
          go install github.com/jstemmer/go-junit-report/v2@14d61e6e75e3f3c74551d757ad936e8e88014464
        # yamllint enable rule:line-length

      - name: Verify the Go modules
        run: |-
          # go mod verify
          go mod verify

      - name: Download the Go modules
        run: |-
          # go mod download
          go mod download

      - name: Run coverage tests
        run: |-
          # go test -v ./... -race
          go test -v ./... \
            -race \
            -json \
            -covermode=atomic \
            -coverprofile=go-test-coverage.out \
          > tests.json

      - name: Show coverage report summary
        run: |-
          go tool cover \
            -func=go-test-coverage.out

      - name: Upload coverage reports to Codecov
        if: ${{ env.CODECOV_TOKEN != '' && !cancelled() }}
        # yamllint disable-line rule:line-length
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: go-cover
          files: go-test-coverage.out
          flags: unit-tests

      - name: Process test results
        if: ${{ !cancelled() }}
        run: |-
          # go-junit-report -parser gojson
          cat tests.json \
          | go-junit-report -parser gojson > go-test-results.xml
          rm tests.json

      - name: Upload test results to Codecov
        if: ${{ env.CODECOV_TOKEN != '' && !cancelled() }}
        # yamllint disable-line rule:line-length
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: go-test-results.xml
          name: go-tests

      - name: Process test results
        if: ${{ !cancelled() }}
        run: |-
          # go-junit-report -parser gojson
          cat tests.json \
          | go-junit-report -parser gojson > go-test-results.xml
          rm tests.json

      - name: Upload test results to Codecov
        if: ${{ env.CODECOV_TOKEN != '' && !cancelled() }}
        # yamllint disable-line rule:line-length
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: go-tests
          files: go-test-results.xml
          report_type: test_results
