---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: Go Integrations
run-name: >-
  Go Integrations for ${{ github.event.pull_request.title || github.sha }}

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        version:
          - '1.26'
      fail-fast: false

    name: Test (v${{ matrix.version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkout the repository
    concurrency:
      # yamllint disable-line rule:line-length
      group: ${{ github.repository }}:${{ github.ref }}:go:test:${{ matrix.version }}
      cancel-in-progress: true

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go v${{ matrix.version }}
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.version }}
          cache-dependency-path: go.sum

      - name: Install go-junit-report
        # yamllint disable rule:line-length
        run: |-
          # go install github.com/jstemmer/go-junit-report
          go install github.com/jstemmer/go-junit-report/v2@14d61e6e75e3f3c74551d757ad936e8e88014464
        # yamllint enable rule:line-length

      - name: Verify the Go modules
        run: |-
          # go mod verify
          go mod verify

      - name: Download the Go modules
        run: |-
          # go mod download
          go mod download

      - name: Run standard tests
        run: |-
          # go test -v ./... -race
          go test -v ./... \
            -race \
            -json \
          > tests.json

      - name: Process test results
        if: ${{ !cancelled() }}
        env:
          GO_TEST_RESULTS_PATH: go-v${{ matrix.version }}-test-results.xml
        run: |-
          # go-junit-report -parser gojson
          cat tests.json \
          | go-junit-report -parser gojson > "${GO_TEST_RESULTS_PATH}"
          rm tests.json

      - name: Generate test report
        if: ${{ !cancelled() }}
        # yamllint disable-line rule:line-length
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        with:
          name: Go v${{ matrix.version }} Tests
          path: go-v${{ matrix.version }}-test-results.xml
          reporter: java-junit

      - name: Upload test results
        if: ${{ !cancelled() }}
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: go-v${{ matrix.version }}-test-results.xml
          path: go-v${{ matrix.version }}-test-results.xml
          if-no-files-found: warn
          archive: false

  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkout the repository
    concurrency:
      group: ${{ github.repository }}:${{ github.ref }}:go:lint
      cancel-in-progress: true

    steps:
      - name: Checkout the repository
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        # yamllint disable-line rule:line-length
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          cache: true

      - name: Run golangci-lint
        # yamllint disable-line rule:line-length
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.12.2

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    permissions:
      contents: read # checkout the repository
    concurrency:
      group: ${{ github.repository }}:${{ github.ref }}:go:build
      cancel-in-progress: true

    steps:
      - name: Checkout the repository
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          # Setting fetch-depth to 0 here should fetch all of the history and
          # all of the tags for the current branch being built
          fetch-depth: 0

      - name: Set up Go
        # yamllint disable-line rule:line-length
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          # Don't cache allow caches to be used for the build to avoid potential
          # poisoning of the build cache with malicious dependencies.
          cache: false

      - name: Login to GitHub Container Registry
        # yamllint disable-line rule:line-length
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        id: releaser
        # yamllint disable-line rule:line-length
        uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: ~> v2
          args: >-
            release
            --clean
            --skip publish
            --snapshot
            --timeout 5m

      - name: Upload linux_amd64_v3
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: afon_linux_amd64_v3
          path: dist/afon_linux_amd64_v3/
          # If there are no files found when uploading this artifact, then there
          # was an issue with the build, so fail and fix rather than permit the
          # pull request to continue and merge, potentially breaking the release
          if-no-files-found: error

      - name: Upload linux_arm64
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: afon_linux_arm64
          path: dist/afon_linux_arm64_v8.0/
          if-no-files-found: error

      - name: Upload linux_arm_7
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: afon_linux_arm_7
          path: dist/afon_linux_arm_7/
          if-no-files-found: error

      - name: Upload darwin_arm64
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: afon_darwin_arm64
          path: dist/afon_darwin_arm64_v8.0/
          if-no-files-found: error

      - name: Upload windows_amd64_v3
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: afon_windows_amd64_v3
          path: dist/afon_windows_amd64_v3/
          if-no-files-found: error

      - name: Upload windows_arm64
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: afon_windows_arm64
          path: dist/afon_windows_arm64_v8.0/
          if-no-files-found: error

      - name: Upload Metadata
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: goreleaser-metadata
          path: dist/*.json
          if-no-files-found: warn
